/*
 * Copyright (c) 2007, 2024 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.jaxws.wsi.j2w.document.literal.R2201;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.StringTokenizer;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import com.sun.ts.tests.jaxws.common.BaseClient;
import com.sun.ts.tests.jaxws.sharedclients.ClientFactory;
import com.sun.ts.tests.jaxws.sharedclients.SOAPClient;
import com.sun.ts.tests.jaxws.sharedclients.doclitclient.J2WDLShared;
import com.sun.ts.tests.jaxws.sharedclients.doclitclient.J2WDLSharedClient;
import com.sun.ts.tests.jaxws.wsi.constants.DescriptionConstants;
import com.sun.ts.tests.jaxws.wsi.constants.SOAPConstants;
import com.sun.ts.tests.jaxws.wsi.utils.DescriptionUtils;

public class Client extends BaseClient implements DescriptionConstants, SOAPConstants {
	/**
	 * The client.
	 */
	private SOAPClient client;

	static J2WDLShared service = null;

	private static final Logger logger = (Logger) System.getLogger(Client.class.getName());

	/**
	 * @class.testArgs: -ap jaxws-url-props.dat
	 * @class.setup_props: webServerHost; webServerPort; platform.mode;
	 *
	 * @param args
	 * @param properties
	 *
	 * @throws Exception
	 */
	@BeforeEach
	public void setup() throws Exception {
		super.setup();
		client = ClientFactory.getClient(J2WDLSharedClient.class, service);
		logger.log(Level.INFO, "setup ok");
	}

	@AfterEach
	public void cleanup() {
		logger.log(Level.INFO, "cleanup");
	}

	/**
	 * @testName: testPartAttributeContents
	 *
	 * @assertion_ids: WSI:SPEC:R2201
	 *
	 * @test_Strategy: Retrieve the WSDL, generated by the Java-to-WSDL tool, and
	 *                 examine all binding elements' operation elements' soap:body
	 *                 elements, ensuring that no more than one part is listed in
	 *                 each part attribute - if present.
	 * 
	 * @throws Exception
	 */
	@Test
	public void testPartAttributeContents() throws Exception {
		Document document = client.getDocument();
		Element[] bindings = DescriptionUtils.getBindings(document);
		for (int i = 0; i < bindings.length; i++) {
			verifyBinding(bindings[i]);
		}
	}

	protected void verifyBinding(Element binding) throws Exception {
		Element[] operations = DescriptionUtils.getChildElements(binding, WSDL_NAMESPACE_URI,
				WSDL_OPERATION_LOCAL_NAME);
		for (int i = 0; i < operations.length; i++) {
			verifyOperation(operations[i]);
		}
	}

	protected void verifyOperation(Element operation) throws Exception {
		NodeList list = operation.getElementsByTagNameNS(SOAP_NAMESPACE_URI, SOAP_BODY_LOCAL_NAME);
		for (int i = 0; i < list.getLength(); i++) {
			verifySOAPBody((Element) list.item(i));
		}
	}

	protected void verifySOAPBody(Element body) throws Exception {
		Attr attr = body.getAttributeNode(SOAP_PARTS_ATTR);
		if (attr == null) {
			return;
		}
		String parts = attr.getValue();
		StringTokenizer tokenizer = new StringTokenizer(parts, " ");
		int count = tokenizer.countTokens();
		if (count > 1) {
			throw new Exception(
					"soap:body element encountered with " + count + " parts listed in its part attribute (BP-R2201)");
		}
	}
}
