/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.jaxws.wsi.j2w.rpc.literal.R2206;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.sun.ts.tests.jaxws.common.BaseClient;
import com.sun.ts.tests.jaxws.sharedclients.ClientFactory;
import com.sun.ts.tests.jaxws.sharedclients.SOAPClient;
import com.sun.ts.tests.jaxws.sharedclients.rpclitclient.J2WRLShared;
import com.sun.ts.tests.jaxws.sharedclients.rpclitclient.J2WRLSharedClient;
import com.sun.ts.tests.jaxws.wsi.constants.DescriptionConstants;
import com.sun.ts.tests.jaxws.wsi.constants.SchemaConstants;
import com.sun.ts.tests.jaxws.wsi.utils.DescriptionUtils;

public class Client extends BaseClient implements DescriptionConstants, SchemaConstants {
	/**
	 * The client.
	 */
	private SOAPClient client;

	static J2WRLShared service = null;

	/**
	 * The document.
	 */
	private Document document;

	private static final Logger logger = (Logger) System.getLogger(Client.class.getName());

	/**
	 * @class.testArgs: -ap jaxws-url-props.dat
	 * @class.setup_props: webServerHost; webServerPort; platform.mode;
	 *
	 * @param args
	 * @param properties
	 *
	 * @throws Exception
	 */
	@BeforeEach
	public void setup() throws Exception {
		super.setup();
		client = ClientFactory.getClient(J2WRLSharedClient.class, service);
		logger.log(Level.INFO, "setup ok");
	}

	@AfterEach
	public void cleanup() {

		logger.log(Level.INFO, "cleanup");
	}

	/**
	 * @testName: testElementParts
	 *
	 * @assertion_ids: WSI:SPEC:R2206
	 *
	 * @test_Strategy: Retrieve the WSDL, generated by the Java-to-WSDL tool, and
	 *                 examine all message elements and verify all part elements,
	 *                 defined by the element attribute, ensuring that they
	 *                 reference a global element.
	 * 
	 * @throws Exception
	 */
	@Test
	public void testElementParts() throws Exception {
		document = client.getDocument();
		Element[] messages = DescriptionUtils.getMessages(document);
		for (int i = 0; i < messages.length; i++) {
			verifyMessage(messages[i]);
		}
	}

	protected void verifyMessage(Element message) throws Exception {
		Element[] parts = DescriptionUtils.getChildElements(message, WSDL_NAMESPACE_URI, WSDL_PART_LOCAL_NAME);
		for (int i = 0; i < parts.length; i++) {
			verifyPart(parts[i]);
		}
	}

	protected void verifyPart(Element part) throws Exception {
		Attr attr = part.getAttributeNode(WSDL_ELEMENT_ATTR);
		if (attr == null) {
			return;
		}
		String value = attr.getValue();
		int index = value.indexOf(':');
		String prefix = value.substring(0, index);
		String name = value.substring(index + 1);
		System.out.println("name =" + name);
		System.out.println("prefix =" + prefix);
		String namespaceURI = DescriptionUtils.getNamespaceURI(part, prefix);
		System.out.println("namespaceURI =" + namespaceURI);
		if (namespaceURI == null) {
			throw new Exception("xmlns:" + prefix + " not defined (BP-R2206)");
		}
		System.out.println("----------------------------");
	}

}
