/*
 * Copyright (c) 2007, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

/*
 * $Id$
 */

package com.sun.ts.tests.jaxws.wsi.j2w.rpc.literal.R2720;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.sun.ts.tests.jaxws.common.BaseClient;
import com.sun.ts.tests.jaxws.sharedclients.ClientFactory;
import com.sun.ts.tests.jaxws.sharedclients.SOAPClient;
import com.sun.ts.tests.jaxws.sharedclients.rpclitclient.J2WRLShared;
import com.sun.ts.tests.jaxws.sharedclients.rpclitclient.J2WRLSharedClient;
import com.sun.ts.tests.jaxws.wsi.constants.DescriptionConstants;
import com.sun.ts.tests.jaxws.wsi.constants.SOAPConstants;
import com.sun.ts.tests.jaxws.wsi.utils.DescriptionUtils;

public class Client extends BaseClient implements DescriptionConstants, SOAPConstants {
	/**
	 * The client.
	 */
	private SOAPClient client;

	static J2WRLShared service = null;

	private static final Logger logger = (Logger) System.getLogger(Client.class.getName());

	/**
	 * @class.testArgs: -ap jaxws-url-props.dat
	 * @class.setup_props: webServerHost; webServerPort; platform.mode;
	 *
	 * @param args
	 * @param properties
	 *
	 * @throws Exception
	 */
	@BeforeEach
	public void setup() throws Exception {
		super.setup();
		client = ClientFactory.getClient(J2WRLSharedClient.class, service);
		logger.log(Level.INFO, "setup ok");
	}

	@AfterEach
	public void cleanup() {

		logger.log(Level.INFO, "cleanup");
	}

	/**
	 * @testName: testPartAttributes
	 *
	 * @assertion_ids: WSI:SPEC:R2720
	 *
	 * @test_Strategy: Retrieve the WSDL, generated by the Java-to-WSDL tool, and
	 *                 examine the wsdl:binding elements, ensuring that the input
	 *                 and output elements' header and headerfault elements have the
	 *                 part attributes and that they're NMTOKENs.
	 *
	 * @throws Exception
	 */
	@Test
	public void testPartAttributes() throws Exception {
		Document document = client.getDocument();
		Element[] bindings = DescriptionUtils.getBindings(document);
		for (int i = 0; i < bindings.length; i++) {
			verifyBinding(bindings[i]);
		}
	}

	protected void verifyBinding(Element binding) throws Exception {
		Element[] operations = DescriptionUtils.getChildElements(binding, WSDL_NAMESPACE_URI,
				WSDL_OPERATION_LOCAL_NAME);
		for (int i = 0; i < operations.length; i++) {
			verifyOperation(operations[i]);
		}
	}

	protected void verifyOperation(Element operation) throws Exception {
		Element[] children = DescriptionUtils.getChildElements(operation, WSDL_NAMESPACE_URI, null);
		for (int i = 0; i < children.length; i++) {
			String localName = children[i].getLocalName();
			if ((localName.equals(WSDL_INPUT_LOCAL_NAME)) || (localName.equals(WSDL_OUTPUT_LOCAL_NAME))) {
				verifyInputOutput(children[i]);
			}
		}
	}

	protected void verifyInputOutput(Element element) throws Exception {
		Element[] children = DescriptionUtils.getChildElements(element, SOAP_NAMESPACE_URI, null);
		for (int i = 0; i < children.length; i++) {
			String localName = children[i].getLocalName();
			if ((localName.equals(SOAP_HEADER_LOCAL_NAME)) || (localName.equals(SOAP_HEADERFAULT_LOCAL_NAME))) {
				verifyPartAttribute(children[i]);
			}
		}
	}

	protected void verifyPartAttribute(Element element) throws Exception {
		String localName = element.getLocalName();
		Attr attr = element.getAttributeNode(SOAP_PART_ATTR);
		if (attr == null) {
			throw new Exception("Required attribute 'part' not found on element '" + localName + "' (BP-R2720)");
		}
		String value = attr.getValue().trim();
		if (value.length() == 0) {
			throw new Exception("Required attribute 'part' on element '" + localName + "' is empty (BP-R2720)");
		}
		if ((value.indexOf(':') != -1) || (value.indexOf(':') != -1)) {
			throw new Exception("Attribute 'part' with value '" + value + "' on element '" + localName
					+ "' is no a valid NMTOKEN (BP-R2720)");
		}
	}
}
